# Generated by Django 6.0.3 on 2026-03-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(blank=True, null=True)),
                ('content', models.CharField()),
                ('image', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
