# Generated by Django 5.2.3 on 2026-04-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_like_total_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='total_likes',
        ),
        migrations.AddField(
            model_name='post',
            name='total_likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
