# Generated by Django 5.2.3 on 2026-04-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='total_likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
